apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-database-deployment
spec:
  selector:
    matchLabels:
      app: yolo-database
  replicas: 1
  template:
    metadata:
      labels:
        app: yolo-database
    spec:
      containers:
        - name: yolo-database
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: database-volume
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: yolo-secrets
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: yolo-secrets
                  key: MONGO_INITDB_ROOT_PASSWORD
      volumes:
        - name: database-volume
          persistentVolumeClaim:
            claimName: yolo-database-claim
