apiVersion: v1
kind: Service
metadata:
  name: yolo-database-service
spec:
  selector:
    app: yolo-database
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017